"""initial schema

Revision ID: 8e2c30995dca
Revises:
Create Date: 2026-06-09 17:01:23.958732+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8e2c30995dca"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role", sa.Enum("student", "interviewer", "admin", name="user_role"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position('@' in email) > 1", name=op.f("ck_users_email_shape")),
        sa.CheckConstraint("rating >= 0", name=op.f("ck_users_rating_non_negative")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(
        "ix_users_active_recent",
        "users",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "questions",
        sa.Column("slug", sa.String(length=140), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("constraints_md", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("code", "mcq", "sql", "system_design", "behavioral", name="question_type"),
            nullable=False,
        ),
        sa.Column(
            "difficulty", sa.Enum("easy", "medium", "hard", name="difficulty"), nullable=False
        ),
        sa.Column("topic", sa.String(length=80), nullable=False),
        sa.Column(
            "tags", postgresql.ARRAY(sa.String(length=40)), server_default="{}", nullable=False
        ),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("pass_count", sa.Integer(), nullable=False),
        sa.Column("time_limit_ms", sa.Integer(), nullable=False),
        sa.Column("memory_limit_mb", sa.Integer(), nullable=False),
        sa.Column(
            "allowed_languages",
            postgresql.ARRAY(sa.String(length=20)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "starter_code",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("reference_solution", sa.Text(), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_ai_generated", sa.Boolean(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "memory_limit_mb BETWEEN 16 AND 2048", name=op.f("ck_questions_memory_limit_range")
        ),
        sa.CheckConstraint(
            "pass_count <= attempt_count", name=op.f("ck_questions_pass_le_attempt")
        ),
        sa.CheckConstraint(
            "time_limit_ms BETWEEN 100 AND 60000", name=op.f("ck_questions_time_limit_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_questions_created_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
        sa.UniqueConstraint("slug", name=op.f("uq_questions_slug")),
    )
    op.create_index(op.f("ix_questions_created_at"), "questions", ["created_at"], unique=False)
    op.create_index(
        "ix_questions_fts",
        "questions",
        [sa.literal_column("to_tsvector('english', title || ' ' || prompt)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_questions_selector",
        "questions",
        ["type", "difficulty", "rating"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "ix_questions_tags", "questions", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_questions_topic"), "questions", ["topic"], unique=False)
    op.create_index(
        "ix_questions_topic_active",
        "questions",
        ["topic", "difficulty"],
        unique=False,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index(
        op.f("ix_refresh_tokens_created_at"), "refresh_tokens", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_tokens_family_id"), "refresh_tokens", ["family_id"], unique=False
    )
    op.create_index(
        "ix_refresh_tokens_user_active", "refresh_tokens", ["user_id", "expires_at"], unique=False
    )
    op.create_table(
        "test_sessions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "topics", postgresql.ARRAY(sa.String(length=80)), server_default="{}", nullable=False
        ),
        sa.Column(
            "question_types",
            postgresql.ARRAY(sa.String(length=20)),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "target_difficulty", sa.Enum("easy", "medium", "hard", name="difficulty"), nullable=True
        ),
        sa.Column("is_adaptive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "submitted",
                "auto_submitted",
                "expired",
                "abandoned",
                name="session_status",
            ),
            nullable=False,
        ),
        sa.Column("violation_count", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column(
            "debrief", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_seconds BETWEEN 60 AND 21600", name=op.f("ck_test_sessions_duration_range")
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_test_sessions_window_ordered")),
        sa.CheckConstraint(
            "violation_count >= 0", name=op.f("ck_test_sessions_violations_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_test_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_sessions")),
    )
    op.create_index(
        op.f("ix_test_sessions_created_at"), "test_sessions", ["created_at"], unique=False
    )
    op.create_index(
        "ix_test_sessions_expiring",
        "test_sessions",
        ["ends_at"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "ix_test_sessions_user_recent", "test_sessions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "topic_mastery",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("topic", sa.String(length=80), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("passes", sa.Integer(), nullable=False),
        sa.Column(
            "last_difficulty", sa.Enum("easy", "medium", "hard", name="difficulty"), nullable=True
        ),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("passes <= attempts", name=op.f("ck_topic_mastery_passes_le_attempts")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_topic_mastery_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_mastery")),
        sa.UniqueConstraint("user_id", "topic", name="user_topic"),
    )
    op.create_index(
        op.f("ix_topic_mastery_created_at"), "topic_mastery", ["created_at"], unique=False
    )
    op.create_index("ix_topic_mastery_user", "topic_mastery", ["user_id", "rating"], unique=False)
    op.create_table(
        "interview_rooms",
        sa.Column("join_code", sa.String(length=12), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("host_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=True),
        sa.Column(
            "status", sa.Enum("waiting", "live", "ended", name="room_status"), nullable=False
        ),
        sa.Column("language", sa.String(length=20), nullable=False),
        sa.Column("document", sa.Text(), nullable=False),
        sa.Column("document_version", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("snapshot_at_version", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_recorded", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column(
            "feedback", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_version >= snapshot_at_version",
            name=op.f("ck_interview_rooms_version_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["users.id"],
            name=op.f("fk_interview_rooms_host_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_interview_rooms_question_id_questions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview_rooms")),
    )
    op.create_index(
        op.f("ix_interview_rooms_created_at"), "interview_rooms", ["created_at"], unique=False
    )
    op.create_index(
        "ix_interview_rooms_host", "interview_rooms", ["host_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_interview_rooms_join_code"), "interview_rooms", ["join_code"], unique=True
    )
    op.create_index(
        op.f("ix_interview_rooms_last_activity_at"),
        "interview_rooms",
        ["last_activity_at"],
        unique=False,
    )
    op.create_index(
        "ix_interview_rooms_open",
        "interview_rooms",
        ["last_activity_at"],
        unique=False,
        postgresql_where=sa.text("status <> 'ended'"),
    )
    op.create_table(
        "test_cases",
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("stdin", sa.Text(), nullable=False),
        sa.Column("expected_stdout", sa.Text(), nullable=False),
        sa.Column("is_sample", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("weight > 0", name=op.f("ck_test_cases_weight_positive")),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_test_cases_question_id_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_cases")),
        sa.UniqueConstraint("question_id", "ordinal", name="question_ordinal"),
    )
    op.create_index(op.f("ix_test_cases_created_at"), "test_cases", ["created_at"], unique=False)
    op.create_index(
        "ix_test_cases_sample",
        "test_cases",
        ["question_id"],
        unique=False,
        postgresql_where=sa.text("is_sample"),
    )
    op.create_table(
        "violations",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "tab_blur",
                "fullscreen_exit",
                "paste_large",
                "copy",
                "devtools",
                "multiple_sessions",
                name="violation_kind",
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum("warned", "logged", "auto_submitted", name="violation_action"),
            nullable=False,
        ),
        sa.Column("running_count", sa.Integer(), nullable=False),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["test_sessions.id"],
            name=op.f("fk_violations_session_id_test_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_violations_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_violations")),
    )
    op.create_index(op.f("ix_violations_created_at"), "violations", ["created_at"], unique=False)
    op.create_index(
        "ix_violations_session_time", "violations", ["session_id", "created_at"], unique=False
    )
    op.create_table(
        "room_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_room_events_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["interview_rooms.id"],
            name=op.f("fk_room_events_room_id_interview_rooms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_events")),
        sa.UniqueConstraint("room_id", "version", name="room_version"),
    )
    op.create_index(op.f("ix_room_events_created_at"), "room_events", ["created_at"], unique=False)
    op.create_index("ix_room_events_replay", "room_events", ["room_id", "version"], unique=False)
    op.create_table(
        "room_participants",
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("interviewer", "candidate", "observer", name="room_role"),
            nullable=False,
        ),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connection_epoch", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["interview_rooms.id"],
            name=op.f("fk_room_participants_room_id_interview_rooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_room_participants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_room_participants")),
        sa.UniqueConstraint("room_id", "user_id", name="room_user"),
    )
    op.create_index(
        op.f("ix_room_participants_created_at"), "room_participants", ["created_at"], unique=False
    )
    op.create_index(
        "ix_room_participants_room_role", "room_participants", ["room_id", "role"], unique=False
    )
    op.create_table(
        "submissions",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("room_id", sa.UUID(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=True),
        sa.Column(
            "type",
            sa.Enum("code", "mcq", "sql", "system_design", "behavioral", name="question_type"),
            nullable=False,
        ),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("source_code", sa.Text(), nullable=False),
        sa.Column(
            "answer", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("is_dry_run", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued", "running", "completed", "failed", "cancelled", name="submission_status"
            ),
            nullable=False,
        ),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("worker_id", sa.String(length=120), nullable=True),
        sa.Column("enqueued_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("queue_wait_ms", sa.Integer(), nullable=False),
        sa.Column("execution_ms", sa.Integer(), nullable=False),
        sa.Column("peak_memory_kb", sa.BigInteger(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("cases_passed", sa.Integer(), nullable=False),
        sa.Column("cases_total", sa.Integer(), nullable=False),
        sa.Column("compile_output", sa.Text(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=False),
        sa.Column("ai_review_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("attempt >= 0", name=op.f("ck_submissions_attempt_non_negative")),
        sa.CheckConstraint(
            "cases_passed <= cases_total", name=op.f("ck_submissions_cases_consistent")
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= max_score", name=op.f("ck_submissions_score_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_submissions_question_id_questions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["interview_rooms.id"],
            name=op.f("fk_submissions_room_id_interview_rooms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["test_sessions.id"],
            name=op.f("fk_submissions_session_id_test_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_submissions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submissions")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="user_idempotency"),
    )
    op.create_index(op.f("ix_submissions_created_at"), "submissions", ["created_at"], unique=False)
    op.create_index(
        "ix_submissions_graded",
        "submissions",
        ["user_id", "question_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'completed' AND NOT is_dry_run"),
    )
    op.create_index(
        "ix_submissions_inflight",
        "submissions",
        ["started_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "ix_submissions_question_recent", "submissions", ["question_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_submissions_session", "submissions", ["session_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_submissions_user_recent", "submissions", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "ai_interactions",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("submission_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("room_id", sa.UUID(), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum(
                "code_review",
                "follow_up",
                "hint",
                "question_gen",
                "behavioral_grade",
                "session_debrief",
                name="ai_purpose",
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "response", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("ok", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("cached", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "prompt_tokens >= 0 AND completion_tokens >= 0",
            name=op.f("ck_ai_interactions_tokens_non_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["interview_rooms.id"],
            name=op.f("fk_ai_interactions_room_id_interview_rooms"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["test_sessions.id"],
            name=op.f("fk_ai_interactions_session_id_test_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_ai_interactions_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_interactions_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_interactions")),
    )
    op.create_index(
        "ix_ai_interactions_budget",
        "ai_interactions",
        ["user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("NOT cached AND ok"),
    )
    op.create_index(
        op.f("ix_ai_interactions_created_at"), "ai_interactions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_ai_interactions_prompt_hash"), "ai_interactions", ["prompt_hash"], unique=False
    )
    op.create_index(
        "ix_ai_interactions_purpose_time",
        "ai_interactions",
        ["purpose", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_interactions_submission", "ai_interactions", ["submission_id"], unique=False
    )
    op.create_table(
        "session_items",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("draft_language", sa.String(length=20), nullable=True),
        sa.Column("draft_code", sa.Text(), nullable=False),
        sa.Column(
            "draft_answer",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("last_saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("final_submission_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False),
        sa.Column("time_spent_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= max_score", name=op.f("ck_session_items_score_in_range")
        ),
        sa.ForeignKeyConstraint(
            ["final_submission_id"],
            ["submissions.id"],
            name=op.f("fk_session_items_final_submission_id_submissions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_session_items_question_id_questions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["test_sessions.id"],
            name=op.f("fk_session_items_session_id_test_sessions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_items")),
        sa.UniqueConstraint("session_id", "ordinal", name="session_ordinal"),
        sa.UniqueConstraint("session_id", "question_id", name="session_question"),
    )
    op.create_index(
        op.f("ix_session_items_created_at"), "session_items", ["created_at"], unique=False
    )
    op.create_table(
        "submission_results",
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("test_case_id", sa.UUID(), nullable=True),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column(
            "outcome",
            sa.Enum(
                "passed",
                "wrong_answer",
                "timeout",
                "runtime_error",
                "compile_error",
                "memory_exceeded",
                "output_truncated",
                "internal_error",
                name="test_case_outcome",
            ),
            nullable=False,
        ),
        sa.Column("execution_ms", sa.Integer(), nullable=False),
        sa.Column("memory_kb", sa.BigInteger(), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("stdout", sa.Text(), nullable=False),
        sa.Column("stderr", sa.Text(), nullable=False),
        sa.Column("is_visible", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["submission_id"],
            ["submissions.id"],
            name=op.f("fk_submission_results_submission_id_submissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["test_case_id"],
            ["test_cases.id"],
            name=op.f("fk_submission_results_test_case_id_test_cases"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_submission_results")),
        sa.UniqueConstraint("submission_id", "ordinal", name="submission_ordinal"),
    )
    op.create_index(
        "ix_submission_results_case_outcome",
        "submission_results",
        ["test_case_id", "outcome"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_submission_results_case_outcome", table_name="submission_results")
    op.drop_table("submission_results")
    op.drop_index(op.f("ix_session_items_created_at"), table_name="session_items")
    op.drop_table("session_items")
    op.drop_index("ix_ai_interactions_submission", table_name="ai_interactions")
    op.drop_index("ix_ai_interactions_purpose_time", table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_prompt_hash"), table_name="ai_interactions")
    op.drop_index(op.f("ix_ai_interactions_created_at"), table_name="ai_interactions")
    op.drop_index(
        "ix_ai_interactions_budget",
        table_name="ai_interactions",
        postgresql_where=sa.text("NOT cached AND ok"),
    )
    op.drop_table("ai_interactions")
    op.drop_index("ix_submissions_user_recent", table_name="submissions")
    op.drop_index("ix_submissions_session", table_name="submissions")
    op.drop_index("ix_submissions_question_recent", table_name="submissions")
    op.drop_index(
        "ix_submissions_inflight",
        table_name="submissions",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_index(
        "ix_submissions_graded",
        table_name="submissions",
        postgresql_where=sa.text("status = 'completed' AND NOT is_dry_run"),
    )
    op.drop_index(op.f("ix_submissions_created_at"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index("ix_room_participants_room_role", table_name="room_participants")
    op.drop_index(op.f("ix_room_participants_created_at"), table_name="room_participants")
    op.drop_table("room_participants")
    op.drop_index("ix_room_events_replay", table_name="room_events")
    op.drop_index(op.f("ix_room_events_created_at"), table_name="room_events")
    op.drop_table("room_events")
    op.drop_index("ix_violations_session_time", table_name="violations")
    op.drop_index(op.f("ix_violations_created_at"), table_name="violations")
    op.drop_table("violations")
    op.drop_index(
        "ix_test_cases_sample", table_name="test_cases", postgresql_where=sa.text("is_sample")
    )
    op.drop_index(op.f("ix_test_cases_created_at"), table_name="test_cases")
    op.drop_table("test_cases")
    op.drop_index(
        "ix_interview_rooms_open",
        table_name="interview_rooms",
        postgresql_where=sa.text("status <> 'ended'"),
    )
    op.drop_index(op.f("ix_interview_rooms_last_activity_at"), table_name="interview_rooms")
    op.drop_index(op.f("ix_interview_rooms_join_code"), table_name="interview_rooms")
    op.drop_index("ix_interview_rooms_host", table_name="interview_rooms")
    op.drop_index(op.f("ix_interview_rooms_created_at"), table_name="interview_rooms")
    op.drop_table("interview_rooms")
    op.drop_index("ix_topic_mastery_user", table_name="topic_mastery")
    op.drop_index(op.f("ix_topic_mastery_created_at"), table_name="topic_mastery")
    op.drop_table("topic_mastery")
    op.drop_index("ix_test_sessions_user_recent", table_name="test_sessions")
    op.drop_index(
        "ix_test_sessions_expiring",
        table_name="test_sessions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_test_sessions_created_at"), table_name="test_sessions")
    op.drop_table("test_sessions")
    op.drop_index("ix_refresh_tokens_user_active", table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_family_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_created_at"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index(
        "ix_questions_topic_active", table_name="questions", postgresql_where=sa.text("is_active")
    )
    op.drop_index(op.f("ix_questions_topic"), table_name="questions")
    op.drop_index("ix_questions_tags", table_name="questions", postgresql_using="gin")
    op.drop_index(
        "ix_questions_selector", table_name="questions", postgresql_where=sa.text("is_active")
    )
    op.drop_index("ix_questions_fts", table_name="questions", postgresql_using="gin")
    op.drop_index(op.f("ix_questions_created_at"), table_name="questions")
    op.drop_table("questions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index(
        "ix_users_active_recent", table_name="users", postgresql_where=sa.text("is_active")
    )
    op.drop_table("users")
    # ### end Alembic commands ###
